const path = require('path');
const { makeSureFileFolderExist } = require('./makeSureFileFolderExist');
const { writeFileSync } = require('fs');

const createHookFile = destinationFolder => {
  const hookFileText = [
    '// autogenerated - translations hook',
    '',
    `import { createGlobalHook } from "react-lang";`,
    `import type { ITranslations } from "./global";`,
    '',
    'export const useTranslations = createGlobalHook<ITranslations>(',
    '  (lang) => import(`./global/${lang}`),',
    ');',
  ].join('\n');

  const destination = path.resolve(destinationFolder, 'index.ts');
  makeSureFileFolderExist(destination);
  writeFileSync(destination, hookFileText, 'utf8');
};

module.exports = { createHookFile };
