import path from 'path';
import { makeSureFileFolderExist } from './makeSureFileFolderExist';
import { writeFileSync } from 'fs';

export const createHookFile = (destinationFolder: string) => {
  const hookFileText = [
    '// autogenerated - translations hook',
    '',
    `import { createGlobalHook } from "react-lingala";`,
    `import type { ITranslations } from "./global";`,
    '',
    'export const useTranslations = createGlobalHook<ITranslations>(',
    '  (lang) => import(`./global/${lang}`),',
    ');',
  ].join('\n');

  const destination = path.resolve(destinationFolder, 'index.ts');
  makeSureFileFolderExist(destination);
  writeFileSync(destination, hookFileText, 'utf8');
};

