const path = require("path");

const { makeSureFileFolderExist } = require("./makeSureFileFolderExist");
const { writeFileSync } = require("fs");

const createIndexFile = ({ defaultLang, destinationFolder }) => {
  const defaultLangKey = defaultLang.replace("-", "_");

  const indexFileText = [
    "// autogenerated: exporting default lang",
    "",
    `import ${defaultLangKey} from "./${defaultLang}";`,
    "",
    `export const DEFAULT_TRANSLATIONS = ${defaultLangKey};`,
    "",
    "export type ITranslations = typeof DEFAULT_TRANSLATIONS",
  ].join("\n");

  const destination = path.resolve(destinationFolder, "global/index.ts");

  makeSureFileFolderExist(destination);
  writeFileSync(destination, indexFileText, "utf8");
};

module.exports = { createIndexFile };
